### ISSUE TITLE
Not work syncScrollOffsets

### ISSUE THREAD

**Issue by 345ml** [PedroBern/react-native-collapsible-tab-view#26] opened 2020-12-15 09:27 UTC
I tried to send a Pull Request, but was failed by the process.
Instead, I will send a diff of the js file.
Sorry about that.

### Current behavior
Not work syncScrollOffsets.

### Expected behaviour
Work syncScrollOffsets.

### Code sample
It seems to be a `ref` problem.
The `scrollToxxx` method is not being accessed.

```diff
diff --git a/node_modules/react-native-collapsible-tab-view/lib/module/CollapsibleTabView.js b/node_modules/react-native-collapsible-tab-view/lib/module/CollapsibleTabView.js
index f7a3837..4909fe3 100644
--- a/node_modules/react-native-collapsible-tab-view/lib/module/CollapsibleTabView.js
+++ b/node_modules/react-native-collapsible-tab-view/lib/module/CollapsibleTabView.js
@@ -88,14 +88,14 @@ const CollapsibleTabView = ({
 
       if (newOffset !== null) {
         scrollScene({
-          ref: item.value,
+          ref: item.value.getNode(),
           offset,
           animated: false
         });
         listOffset.current[item.key] = offset;
       } else if (itemOffset < headerHeight || !itemOffset) {
         scrollScene({
-          ref: item.value,
+          ref: item.value.getNode(),
           offset: Math.min(offset, headerHeight),
           animated: false
         });
@@ -117,7 +117,7 @@ const CollapsibleTabView = ({
       listRefArr.current.forEach(item => {
         // scroll everything because we could be moving to a new tab
         scrollScene({
-          ref: item.value,
+          ref: item.value.getNode(),
           offset: newOffset,
           animated: true
         });
@@ -169,14 +169,14 @@ const CollapsibleTabView = ({
 
   const buildGetRef = React.useCallback(routeKey => ref => {
     if (ref) {
-      const found = listRefArr.current.find(e => e.key === routeKey);
-
-      if (!found) {
-        listRefArr.current.push({
+      listRefArr.current = listRefArr.current.filter((listRef) => {
+        return listRef.key !== routeKey
+      }).concat(
+        [{
           key: routeKey,
           value: ref
-        });
-      }
+        }]
+      );
     }
   }, []);
   /**
```

**Comment by PedroBern** [comment] 2020-12-15 13:03
Hi @345ml , if you want to use `scrollToOffsets` instead of the current snap, you can do the following:

1. Disable the snap

```jsx
<CollapsibleTabView disableSnap  ... />
```

2. Add the following to your `FlatList` or `ScrollView`

```jsx
<MyComponent scrollToOffsets={[0, HEADER_HEIGHT]} snapToEnd={false} ... />
```

**Comment by PedroBern** [comment] 2020-12-15 13:11
Hi @345ml, can you share a reproducible demo?

**Comment by 345ml** [comment] 2020-12-16 01:48
I'm sorry for the lack of information.
I will prepare a sample code.

**Comment by 345ml** [comment] 2020-12-16 02:25
@PedroBern 
Thanks quick response!!

![collapsed](https://user-images.githubusercontent.com/8254811/102296585-80e66780-3f02-11eb-8911-d9e274ff42d8.gif)

This is a slightly modified version of the Quick start sample code.
The content of the ScrollView has been changed to make the display easier to understand.

```js
import React from 'react';
import { StyleSheet, View, Text, Animated } from 'react-native';
import {
  CollapsibleTabView,
  useCollapsibleScene,
} from 'react-native-collapsible-tab-view';
import { SceneMap } from 'react-native-tab-view';

const SomeRoute = ({
  routeKey,
  color,
}) => {
  const scrollPropsAndRef = useCollapsibleScene(routeKey);

  return (
    <Animated.ScrollView
      style={{ backgroundColor: color }}
      {...scrollPropsAndRef}
    >
      {
        new Array(20).fill(null).map((item, index) => {
          return <Text style={{ padding: 20, color: "red" }}>{index}</Text>;
        })
      }
    </Animated.ScrollView>
  );
};

const FirstScene = () => <SomeRoute routeKey="first" color="white" />;
const SecondScene = () => <SomeRoute routeKey="second" color="black" />;

const HEADER_HEIGHT = 250;

const renderHeader = () => (
  <View style={styles.header}>
    <Text style={styles.headerText}>COLLAPSIBLE</Text>
  </View>
);

const renderScene = SceneMap({
  first: FirstScene,
  second: SecondScene,
});

const App = () => {
  const [index, setIndex] = React.useState(0);
  const [routes] = React.useState([
    { key: 'first', title: 'First' },
    { key: 'second', title: 'Second' },
  ]);

  const handleIndexChange = (index) => {
    setIndex(index);
  };

  return (
    <CollapsibleTabView
      navigationState={{ index, routes }}
      renderScene={renderScene}
      onIndexChange={handleIndexChange}
      renderHeader={renderHeader} // optional
      headerHeight={HEADER_HEIGHT} // optional, will be computed.
    />
  );
};

export default App;

const styles = StyleSheet.create({
  header: {
    height: HEADER_HEIGHT,
    backgroundColor: '#2196f3',
    justifyContent: 'center',
    alignItems: 'center',
    elevation: 4,
  },
  headerText: {
    color: 'white',
    fontSize: 24,
  },
  content: {
    height: 1500,
  },
});

```

**Comment by PedroBern** [comment] 2020-12-29 13:03
Hi @345ml I don't have this bug. Did you test on a real device?

**Comment by ariesbrylle-bms** [comment] 2021-01-11 11:38
Encountered this also, until now, I can't find a solution.

**Comment by 345ml** [comment] 2021-01-12 01:58
@PedroBern 
Sorry for the late reply.
This will be reproduced in the iOS simulator.

However, I feel that it is due to something else rather than a difference in devices.

**Comment by PedroBern** [comment] 2021-01-13 12:13
@345ml can you make a repro on [snack](https://snack.expo.io/)?

**Comment by 345ml** [comment] 2021-01-13 12:39
@PedroBern 
I'm really sorry.
I'm already using another solution and lost the source code...

**Comment by PedroBern** [comment] 2021-01-13 12:54
@345ml no problem. I will let it open, looks like this bug is happening to some people, but I can't reproduce it.

**Comment by matthewwen** [comment] 2021-01-14 03:29
Yeah I have that bug. I'll try to develop a snack for it.

**Comment by matthewwen** [comment] 2021-01-15 18:40
Here is the expo snack for it. https://snack.expo.io/@mattwen2018/collapsibleheader
@PedroBern

**Comment by PedroBern** [comment] 2021-01-15 23:54
@matthewwen thanks, now I'm reproducing the bug. Don't know the cause yet.

**Comment by PedroBern** [comment] 2021-01-16 00:03
@matthewwen after upgrading to expo SDK 40, and updating to the recommended SDK dependencies version, the snack is working.

I will close this now. If somebody experiences this bug in the SDK 40, please comment here and send a repro.

## Solution

Upgrade to SDK 40

**Closed by PedroBern** 2021-01-16 00:03 UTC
Labels: bug

**Comment by matthewwen** [comment] 2021-01-16 00:26
Okay I'm going to take a closer look. I just upgraded to SDK 40 for my project and I still have the problem. It would be nice if this feature works on SDK 37.

**Comment by PedroBern** [comment] 2021-01-16 02:04
😞  On the snack, did you still have the bug on sdk 40?

**Comment by matthewwen** [comment] 2021-01-16 17:55
Yeah. I updated to SDK40 and it works, but when I update to SDK40 on my personal project, it doesn't work.

**Comment by matthewwen** [comment] 2021-01-18 07:08
@PedroBern I think I found the issue, but I'm wondering how did you calculate the "paddingTop", and how does it know if the header expanded or not?

**Comment by PedroBern** [comment] 2021-01-18 12:14
@matthewwen [here is the padding top calculation](https://github.com/PedroBern/react-native-collapsible-tab-view/blob/main/src/useCollapsibleScene.tsx#L56) It does not change.

**Comment by PedroBern** [comment] 2021-01-24 11:29
> Yeah. I updated to SDK40 and it works on the snack, but when I update to SDK40 on my personal project, it doesn't work.

@matthewwen try v3 it is probably fixed now
