### ISSUE TITLE
Can i use Custom ListView?

### ISSUE THREAD

**Issue by waheed25** [PedroBern/react-native-collapsible-tab-view#212] opened 2021-11-15 12:20 UTC
I am already using [recyclerlistview](https://github.com/Flipkart/recyclerlistview) and don't want to use Flatlist due to performance issues of list having images, Is there a way to use that [recyclerlistview](https://github.com/Flipkart/recyclerlistview) instead of Flatlist?

**Comment by 10000multiplier** [comment] 2021-11-18 18:35
This is a duplicate issue. See https://github.com/PedroBern/react-native-collapsible-tab-view/issues/195

**Comment by siddharth-kt** [comment] 2021-12-21 11:35
Did you got any solution ?

**Comment by waheedakhtar694** [comment] 2022-01-13 09:46
@siddharth-kt  No.

**Comment by andreialecu** [comment] 2022-01-15 11:37
Closing as duplicate of #195

**Closed by andreialecu** 2022-01-15 11:37 UTC
Labels: question
