### ISSUE TITLE
Unable to resolve module @react-navigation/material-top-tabs

### ISSUE THREAD

**Issue by 345ml** [PedroBern/react-native-collapsible-tab-view#27] opened 2020-12-15 10:00 UTC
```
bundling failed: Error: Unable to resolve module `@react-navigation/material-top-tabs` from `node_modules/react-native-collapsible-tab-view/lib/module/MaterialTopTabsCollapsibleTabView.js`: @react-navigation/material-top-tabs could not be found within the project.
```

I used it without the integration with react-navigation, but the above error occurs.

**Comment by andreialecu** [comment] 2020-12-15 14:46
`bundling failed` seems like a weird message, and looks related to building the project, not using it.

Can you explain step by step what you did to receive this error?

**Comment by PedroBern** [comment] 2020-12-15 15:12
@andreialecu it seems to happen because we are exporting `createMaterialCollapsibleTopTabNavigator ` and `MaterialTopTabsCollapsibleTabView ` even if `react-navigation` isen't installed. So, `react-navigation` is not added as a dependency, it will break the build.

It's easy to reproduce:

1. Create a new expo project
2. Add `react-native-collapsible-tab-view` and the peers (without `react-navigation`)
3. Copy the quick start code
4. `expo start` should error
5. add the `@react-navigation/...` peers
6. `expo start` works

Note that the quick start code does not use the navigator. So it should work.

I think the solution is to conditionally export `createMaterialCollapsibleTopTabNavigator ` and `MaterialTopTabsCollapsibleTabView `, but I was not successful.

The other option is to remove the `peerDependenciesMeta `, @andreialecu what you think?

**Comment by andreialecu** [comment] 2020-12-15 15:17
I see. I don't use expo so I wasn't familiar with that error signature.

Normally if the material tab files are not imported there shouldn't be any error but I suspect that typescript is interfering. I will take a look in a couple of hours, currently away for a bit.

**Comment by PedroBern** [comment] 2020-12-15 15:27
Thanks @andreialecu! But don't worry, it's not a priority

**Comment by andreialecu** [comment] 2020-12-15 15:49
I'm still on mobile but I figured out what the problem is. It's related to these exports:
https://github.com/PedroBern/react-native-collapsible-tab-view/blob/e58a5f5a18eed700fb741c931c6493ba8e852907/src/index.tsx#L9

They should be in a separate file instead of the index. Perhaps one named navigation.tsx so that end users would imported them from "react-native-collapsible-tab-view/navigation" instead.

**Comment by andreialecu** [comment] 2020-12-15 17:38
Upon further investigation, the problem with my proposed approach above is that because of the path structure of the published package, the imports would end up looking like:

```ts
import { createMaterialCollapsibleTopTabNavigator } from "react-native-collapsible-tab-view/lib/module/navigation"
```

Which isn't a great experience...

There's a proposal here that would allow rewriting the imports so that `react-native-collapsible-tab-view/navigation` would work, but I'm not sure if react native and the metro bundler can use it:
https://nodejs.org/api/packages.html#packages_package_entry_points

Alternatives:

1) Could make the peer non optional, but users still need to ensure it's installed in their projects. Peers usually just show a warning while installing, which most users ignore. And having it non-optional isn't a great approach for people that don't need `react-navigation` integration.

2) Could publish a separate npm package just with the `react-navigation` integration. Might be do-able, but would need restructuring this project to be a monorepo (via yarn workspaces, for example).

**Comment by PedroBern** [comment] 2020-12-15 18:58
@andreialecu thanks for the help. Did a quick modification, adding a `navigation.tsx` to export the navigator, published the `@beta` version to test, and didn't work. Need to import from `.../lib/module/navigation`, and something was broken, because the navigator stopped working in my project.

Seems like the best alternative is the `2` you have pointed, I will look into it in the future, but as right now I don't have much time, I will follow the alternative `1`.

**Comment by PedroBern** [comment] 2020-12-15 19:15
As it isn't an optional dependency anymore (in `v1.4.2`), I'm closing. When there is some extra time, I will look into refactoring into a monorepo.

**Closed by PedroBern** 2020-12-15 19:15 UTC
Labels: bug

**Comment by 345ml** [comment] 2020-12-16 01:46
Good job guys!!!
