### ISSUE TITLE
How do I get the correct ref for a FlatList?

### ISSUE THREAD

**Issue by midoushitongtong** [PedroBern/react-native-collapsible-tab-view#24] opened 2020-12-13 07:26 UTC
hi
I want to use some api on `<FlatList />`, like `scrollToIndex`, but I can't get the ref correctly.

```tsx
<Animated.FlatList
  ref={this.flatListRef}
  {...scenePropsAndRef}
/>

componentDidMount() {
  setTimeout(() => {
    console.log(this.flatListRef.current); // null
  }, 3000);
}
```

What might I have missed?

**Comment by PedroBern** [comment] 2020-12-14 12:13
Hi @midoushitongtong it's a duplicate of #2

**Closed by PedroBern** 2020-12-14 12:13 UTC
Labels: question
