### ISSUE TITLE
Delay on open with react navigation

### ISSUE THREAD

**Issue by picknamexd** [PedroBern/react-native-collapsible-tab-view#155] opened 2021-03-14 13:17 UTC
I have a Tab.Navigator wrapping a Stack.Navigator that calls one Screen that shows a list of users, when I click on one of them, I call the Screen that contains collapsible-tab-view, and when it opens, it has a lot of lag, I have verified that if I put a single Tab, it works fine, but if I add 3 or 4, it starts to have lag, am I doing something wrong?

**Comment by PedroBern** [comment] 2021-03-16 17:24
Does it happen if the content of your tabs are light components, something like an empty view or null? Did you try lazy mode?

**Comment by picknamexd** [comment] 2021-03-16 19:00
Hello! @PedroBern Thanks for your answer, right now I'm only testing the example in the read.me, the tabs are practically empty. I just tried wrapping with Lazy mode and nothing changes, I put the code I am using.

In react navigation first tab screen:

```
const Perfil: React.FC = () => {
  const renderItem: ListRenderItem<number> = React.useCallback(({index}) => {
    return (
      <View style={[styles.box, index % 2 === 0 ? styles.boxB : styles.boxA]} />
    );
  }, []);
  return (
    <Tabs.Container
      HeaderComponent={HeaderComponent}
      headerHeight={HEADER_HEIGHT}
      minHeaderHeight={MIN_HEADER_HEIGHT}
      TabBarComponent={(props) => (
        <MaterialTabBar
          {...props}
          activeColor="black"
          inactiveColor="black"
          inactiveOpacity={1}
          labelStyle={{fontSize: 14}}
        />
      )}>
      <Tabs.Tab name="Tab1" label="A">
        <Tabs.Lazy>
          <Tabs.Container />
        </Tabs.Lazy>
      </Tabs.Tab>
      <Tabs.Tab name="Tab2" label="B">
        <Tabs.Lazy>
          <Tabs.Container />
        </Tabs.Lazy>
      </Tabs.Tab>
      <Tabs.Tab name="Tab3" label="C">
        <Tabs.Lazy>
          <Tabs.Container />
        </Tabs.Lazy>
      </Tabs.Tab>
      <Tabs.Tab name="Tab4" label="D">
        <Tabs.Lazy>
          <Tabs.Container />
        </Tabs.Lazy>
      </Tabs.Tab>
    </Tabs.Container>
  );
};
```

In Navigation Component
```
    return (
<SafeAreaProvider>
        <NavigationContainer
          theme={this.scheme === 'dark' ? DarkTheme : DefaultTheme}>
          ...
            <Tab.Screen name="PerfilStack" component={PerfilStackScreen} />
          </Tab.Navigator>
        </NavigationContainer>
      </SafeAreaProvider>
    );
  }
```

In PerfilStackScreen:

```
return (
<ListadoStack.Navigator>
  ...
   <ListadoStack.Screen name="Perfil" component={Perfil} />
    </ListadoStack.Navigator>
  );
}
```

**Comment by Jalson1982** [comment] 2021-04-21 13:22
I have the same issue. I put 4 same scrollviews and the same problem. JS thread goes down to 20 and UI thread about 55 when I navigate to screen that contains collapsible-tab-view. I tried lazy too but it is the same.

**Comment by andreialecu** [comment] 2021-04-21 14:09
@Jalson1982 and others, is this on Android or iOS?

I think there are some upstream issues with Reanimated because I'm running into: https://github.com/software-mansion/react-native-reanimated/issues/1932 which is somewhat related, but more serious.

**Comment by Jalson1982** [comment] 2021-04-21 14:11
@andreialecu I see it on IOS on Android I am scared to look  . It is very very noticeable that there is some big lag.

**Comment by andreialecu** [comment] 2021-04-21 14:20
Does the JS thread consistently stay down to 20fps, or is it just for the initial load?

If so, a repro would be good to see. 

On the app I'm working on I have a collapsible tab view with 6 lazy loaded scrollable tabs, and on iOS the performance is perfect.

**Comment by Jalson1982** [comment] 2021-04-21 14:21
Ok, repo is very hard to get :(. But basically, it is just scroll view with some text nothing heavy. I can make a video to see drops if you like.

**Comment by andreialecu** [comment] 2021-04-21 14:31
@Jalson1982 try reproducing it on https://github.com/andreialecu/rnctv-react-native-bare-test

It has two tabs, but it doesn't seem to exhibit the problem by default. 

![simulator_screenshot_D91C15CA-20C0-4CD7-A71C-17EDAE5D6936](https://user-images.githubusercontent.com/697707/115571148-66b10180-a2c7-11eb-88e3-23a83bde2e2c.png)


Open a PR with the reproduction on the repository above if you can achieve it.

**Comment by andreialecu** [comment] 2021-06-18 09:27
I believe this may be fixed by #186

**Comment by andreialecu** [comment] 2021-07-28 13:47
4.2.1 should have some pretty huge performance improvements, which I think should resolve this.

Closing, feel free to ping me to reopen if this is still an issue.

**Closed by andreialecu** 2021-07-28 13:47 UTC
Labels: needs repro, waiting for feedback

**Comment by siddharth-kt** [comment] 2021-12-25 18:44
> 4.2.1 should have some pretty huge performance improvements, which I think should resolve this.
> 
> Closing, feel free to ping me to reopen if this is still an issue.

@andreialecu i am using version 2.0.2 with react-navigation + react-native-page-view and i am facing same issue kindly implement such update in react-navigation too.
